### ISSUE TITLE
使用python fishing.py image -f yolox/exp/yolox_tiny_fish.py -c weights/best_tiny3.pth --conf 0.25 --nms 0.45 --tsize 640 --device cpu后提示，无法运行

### ISSUE THREAD

**Issue by a1175815821** [7eu7d7/genshin_auto_fish#11]
Traceback (most recent call last):
  File "fishing.py", line 19, in <module>
    from fisher.predictor import *
  File "C:\Users\hp\Desktop\genshin_auto_fish-master\fisher\predictor.py", line 8, in <module>
    from yolox.data.data_augment import ValTransform
  File "C:\Users\hp\Desktop\genshin_auto_fish-master\yolox\data\__init__.py", line 8, in <module>
    from .datasets import *
  File "C:\Users\hp\Desktop\genshin_auto_fish-master\yolox\data\datasets\__init__.py", line 5, in <module>
    from .coco import COCODataset
  File "C:\Users\hp\Desktop\genshin_auto_fish-master\yolox\data\datasets\coco.py", line 10, in <module>
    from pycocotools.coco import COCO
ModuleNotFoundError: No module named 'pycocotools'

**Comment by wudih146** [comment]
更新下这个模块就好了

**Comment by milkbing** [comment]
> 更新下这个模块就好了

请问，怎么更新呢？
