### ISSUE TITLE
运行python train.py出错

### ISSUE THREAD

**Issue by q764447890** [7eu7d7/genshin_auto_fish#110]
![2](https://user-images.githubusercontent.com/26245718/134815350-9f924d10-283b-4ca7-aef0-e7987e445e61.PNG)

**Comment by Yooofox** [comment]
我的也是这样

Traceback (most recent call last):
  File "train.py", line 25, in <module>
    net.load_state_dict(torch.load(args.resume))
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './output/fish_sim_net.pth'

**Comment by MoOSeeW** [comment]
同 想请教一下如何解决

**Comment by cydn** [comment]
> 我的也是这样
> 
> Traceback (most recent call last): File "train.py", line 25, in net.load_state_dict(torch.load(args.resume)) File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 581, in load with _open_file_like(f, 'rb') as opened_file: File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 230, in _open_file_like return _open_file(name_or_buffer, mode) File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 211, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: './output/fish_sim_net.pth'

我好像把output/fish_sim_net_399.pth改了个名字就好了，但是实际操作还没成功
