### ISSUE TITLE
YOLOX训练工作流程训练流程这里通过不了

### ISSUE THREAD

**Issue by CronusLM** [7eu7d7/genshin_auto_fish#119]
Traceback (most recent call last):
  File "yolox_tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "c:\users\kronus\appdata\local\genshin_auto_fish\yolox\core\__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "c:\users\kronus\appdata\local\genshin_auto_fish\yolox\core\trainer.py", line 12, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\Kronus\.conda\envs\ysfish\lib\site-packages\torch\utils\tensorboard\__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'

路径我用的是绝对路径self.data_dir = "C:\Users\Kronus\AppData\Local\genshin_auto_fish\fish-dataset"
不知道是哪里出现问题

**Comment by Yooofox** [comment]
我的也是
Traceback (most recent call last):
  File "yolox_tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "c:\users\1\git\diaoyu\genshin_auto_fish\yolox\core\__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "c:\users\1\git\diaoyu\genshin_auto_fish\yolox\core\trainer.py", line 12, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\tensorboard\__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'

**Comment by misakamisaka10086** [comment]
缺模块啊 pip install 模块名
