### ISSUE TITLE
  File "requirements.py", line 74, in <module>

### ISSUE THREAD

**Issue by twfusoul** [7eu7d7/genshin_auto_fish#147]
(base) PS C:\Users\杰少> conda activate ysfish
(ysfish) PS C:\Users\杰少> cd genshin_auto_fish
(ysfish) PS C:\Users\杰少\genshin_auto_fish> python -m pip install -U pip
Requirement already satisfied: pip in d:\anaconda3\envs\ysfish\lib\site-packages (21.0.1)
Collecting pip
  Using cached pip-21.3-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.0.1
    Uninstalling pip-21.0.1:
      Successfully uninstalled pip-21.0.1
Successfully installed pip-21.3
(ysfish) PS C:\Users\杰少\genshin_auto_fish> python requirements.py
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 16, in pip_install
    check=True,
  File "D:\anaconda3\envs\ysfish\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

这个是啥问题呢？

**Comment by batvbs** [comment]
> #145

使用历史版本，最新版被 @wasabiegg 塞了一堆bug

历史版本-请复制链接，不要点击打开
https://github.com/7eu7d7/genshin_auto_fish/tree/65b8796dbdb71c67ab5085b6ad348acc2d23c39b
