### ISSUE TITLE
运行钓鱼,出这个,又是什么情况,眼花了

### ISSUE THREAD

**Issue by Eye522** [7eu7d7/genshin_auto_fish#175]
(ysfish) C:\Users\zhanghailing\Desktop\genshin_auto_fish>python fishing.py image -f yolox/exp/yolox_tiny_fish.py -c weights/best_tiny3.pth --conf 0.25 --nms 0.45 --tsize 640 --device gpu
2021-11-15 19:42:39.976 | INFO     | __main__:main:91 - Args: Namespace(ckpt='weights/best_tiny3.pth', conf=0.25, demo='image', device='gpu', exp_file='yolox/exp/yolox_tiny_fish.py', experiment_name='yolox_tiny_fish', fp16=False, fuse=False, legacy=False, model_dir='./weights/fish_genshin_net.pth', n_actions=2, n_states=3, name=None, nms=0.45, path='./assets/dog.jpg', step_tick=12, trt=False, tsize=640)
2021-11-15 19:42:40.116 | INFO     | __main__:main:101 - Model Summary: Params: 5.03M, Gflops: 15.15
2021-11-15 19:42:41.541 | INFO     | __main__:main:114 - loading checkpoint
Traceback (most recent call last):
  File "fishing.py", line 190, in <module>
    main(exp, args)
  File "fishing.py", line 117, in main
    model.load_state_dict(ckpt["model"])
  File "C:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in cu

**Comment by Eye522** [comment]
好吧,已经有解决办法了

**Comment by Lenor-Alter** [comment]
楼主，我也遇到这个问题。请问怎么解决的

**Comment by Eye522** [comment]
下载右边Releases标签里的三个文件放到weights文件夹里,我是可以运行
