### ISSUE TITLE
yolox训练保存报错，numpy 安装1.20.0版本也报一样的错。其他版本torch==1.10.1  torchvision==0.11.2  CU113？

### ISSUE THREAD

**Issue by lhongdong** [7eu7d7/genshin_auto_fish#204]
TA: 0:03:52
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]:318 - Save weights to ./YOLOX_outputs\yolox_tiny_fish
100%|##################################################################################| 17/17 [00:14<00:00,  1.20it/s]
2021-12-23 15:31:59 | INFO     | yolox.evaluators.coco_evaluator:171 - Evaluate in main process...
2021-12-23 15:31:59 | INFO     | yolox.evaluators.coco_evaluator:204 - Loading and preparing results...
2021-12-23 15:32:00 | INFO     | yolox.evaluators.coco_evaluator:204 - DONE (t=0.06s)
2021-12-23 15:32:00 | INFO     | pycocotools.coco:362 - creating index...
2021-12-23 15:32:00 | INFO     | pycocotools.coco:362 - index created!
2021-12-23 15:32:00 | INFO     | yolox.core.trainer:183 - Training of experiment is done and the best AP is 0.00
2021-12-23 15:32:00 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (4808), thread 'MainThread' (9116):
Traceback (most recent call last):

  File "D:\L\Git\genshin_auto_fish\yolox_tools\train.py", line 125, in <module>
    launch(
    └ <function launch at 0x000001E7F9ACB430>

> File "d:\l\git\genshin_auto_fish\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001E7FAAC6160>

  File "D:\L\Git\genshin_auto_fish\yolox_tools\train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001E7F9F253A0>
    └ <yolox.core.trainer.Trainer object at 0x000001E7FAAC7FA0>

  File "d:\l\git\genshin_auto_fish\yolox\core\trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000001E7FAA6BE50>
    └ <yolox.core.trainer.Trainer object at 0x000001E7FAAC7FA0>

  File "d:\l\git\genshin_auto_fish\yolox\core\trainer.py", line 82, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x000001E7FAA7F5E0>
    └ <yolox.core.trainer.Trainer object at 0x000001E7FAAC7FA0>

  File "d:\l\git\genshin_auto_fish\yolox\core\trainer.py", line 207, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x000001E7FAA7F8B0>
    └ <yolox.core.trainer.Trainer object at 0x000001E7FAAC7FA0>

  File "d:\l\git\genshin_auto_fish\yolox\core\trainer.py", line 302, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(
                             │    │   └ <function Exp.eval at 0x000001E7FAAC69D0>
                             │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x000001E7FAAC7FA0>

  File "d:\l\git\genshin_auto_fish\yolox\exp\yolox_base.py", line 288, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x000001E7FAA651F0>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000001E7953392E0>

  File "d:\l\git\genshin_auto_fish\yolox\evaluators\coco_evaluator.py", line 131, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([ 0.9705,  0.1696, 16.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 0, 'category_id': 2, 'bbox': [762.0606689453125, 391.85870361328125, 88.766845703125, 68.79165649414062], 'scor...
                   │    └ <function COCOEvaluator.evaluate_prediction at 0x000001E7FAA65310>
                   └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000001E7953392E0>

  File "d:\l\git\genshin_auto_fish\yolox\evaluators\coco_evaluator.py", line 212, in evaluate_prediction
    cocoEval = COCOeval(cocoGt, cocoDt, annType[1])
               │        │       │       └ ['segm', 'bbox', 'keypoints']
               │        │       └ <pycocotools.coco.COCO object at 0x000001E79531C850>
               │        └ <pycocotools.coco.COCO object at 0x000001E7FD4B5490>
               └ <class 'yolox.layers.fast_coco_eval_api.COCOeval_opt'>

  File "D:\Anaconda3\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
    │    │        │              └ 'bbox'
    │    │        └ <class 'pycocotools.cocoeval.Params'>
    │    └ {}
    └ <yolox.layers.fast_coco_eval_api.COCOeval_opt object at 0x000001E7FABFC9D0>

  File "D:\Anaconda3\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
    │    └ <function Params.setDetParams at 0x000001E799E50D30>
    └ <pycocotools.cocoeval.Params object at 0x000001E7FABFC910>

  File "D:\Anaconda3\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
    │              │  │                  │  └ <function round_ at 0x000001E7EE14B160>
    │              │  │                  └ <module 'numpy' from 'D:\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
    │              │  └ <function linspace at 0x000001E7EE75C790>
    │              └ <module 'numpy' from 'D:\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
    └ <pycocotools.cocoeval.Params object at 0x000001E7FABFC910>

  File "<__array_function__ internals>", line 5, in linspace

  File "D:\Anaconda3\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
          │        │     └ 10.0
          │        └ <built-in function index>
          └ <module 'operator' from 'D:\\Anaconda3\\lib\\operator.py'>

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by HuYo-OS** [comment]
你好，你可以试试把numpy再降级为1.17.0，我之前也是遇到这个问题，亲测管用
