### ISSUE TITLE
YOLOX训练cpu启动错误

### ISSUE THREAD

**Issue by BeidouStarX** [7eu7d7/genshin_auto_fish#218]
由于YOLOX训练没有cuda所以按照YOLOX的github demo在训练指令后加了cpu
即python yolox_tools/train.py -f yolox/exp/yolox_tiny_fish.py -d 1 -b 8 --fp16 -o -c weights/yolox_tiny.pth cpu
导致
Traceback (most recent call last):
  File "yolox_tools/train.py", line 116, in <module>
    exp.merge(args.opts)
  File "d:\genshin_auto_fish\yolox\exp\base_exp.py", line 64, in merge
    assert len(cfg_list) % 2 == 0
AssertionError

**Comment by BeidouStarX** [comment]
改成python yolox_tools/train.py -f yolox/exp/yolox_tiny_fish.py -d 1 -b 8 --fp16 -o -c weights/yolox_tiny.pth --device cpu后是
YOLOX train parser: error: argument -d/--devices: invalid int value: 'cpu'
