### ISSUE TITLE
调一条之后，报错，乱抛杆

### ISSUE THREAD

**Issue by scopion** [7eu7d7/genshin_auto_fish#227]
2022-01-17 16:02:10.488 | INFO     | fisher.predictor:inference:77 - Infer time: 0.3670s
Traceback (most recent call last):
  File "D:\genshin_auto_fish\fisher\environment.py", line 69, in throw_rod
    fish_info = min(list(filter(lambda x: x[0] == fish_type, obj_list)),
ValueError: min() arg is an empty sequence
2022-01-17 16:02:11.015 | INFO     | fisher.predictor:inference:77 - Infer time: 0.3610s
Traceback (most recent call last):
  File "D:\genshin_auto_fish\fisher\environment.py", line 69, in throw_rod
    fish_info = min(list(filter(lambda x: x[0] == fish_type, obj_list)),
ValueError: min() arg is an empty sequence

**Comment by HuYo-OS** [comment]
DQN的问题

**Comment by EmberSuns** [comment]
我也是，你解决了吗

**Comment by lx1169732264** [comment]
我也遇到了这个情况, 在掉了一条后,就开始不断抛竿+秒收竿,鱼连钩都没咬就收上来了

**Comment by HuYo-OS** [comment]
请确认您是在1920*1080分辨率下运行

**Comment by scopion** [comment]
放弃用这个了。
