### ISSUE TITLE
最后一步运行的时候报错，ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by Anhcal** [7eu7d7/genshin_auto_fish#229]
D:\APP\anaconda\envs\genshin_auto_fish-master>python fishing.py image -f yolox/exp/yolox_tiny_fish.py -c weights/best_tiny3.pth --conf 0.25 --nms 0.45 --tsize 640 --device cpu
Traceback (most recent call last):
  File "fishing.py", line 15, in <module>
    from yolox.exp import get_exp
  File "D:\APP\anaconda\envs\genshin_auto_fish-master\yolox\__init__.py", line 4, in <module>
    from .utils import configure_module
  File "D:\APP\anaconda\envs\genshin_auto_fish-master\yolox\utils\__init__.py", line 6, in <module>
    from .boxes import *
  File "D:\APP\anaconda\envs\genshin_auto_fish-master\yolox\utils\boxes.py", line 8, in <module>
    import torchvision
  File "D:\APP\anaconda\envs\genshin_auto_fish-master\lib\site-packages\torchvision\__init__.py", line 7, in <module>
    from torchvision import datasets
  File "D:\APP\anaconda\envs\genshin_auto_fish-master\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module>
    from .lsun import LSUN, LSUNClass
  File "D:\APP\anaconda\envs\genshin_auto_fish-master\lib\site-packages\torchvision\datasets\lsun.py", line 2, in <module>
    from PIL import Image
  File "D:\APP\anaconda\envs\genshin_auto_fish-master\lib\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: DLL load failed: 找不到指定的模块。

再pycharm中配好的环境，pycharm命令行能够运行正常但不是管理员身份鼠标不动，所以在系统命令行运行（管理员和非管理员身份）出现以上问题。

**Comment by HuYo-OS** [comment]
你好！你可以试试右键桌面的pycharm图标选择以管理员身份运行
