### ISSUE TITLE
torch版本必须1.7.0吗？

### ISSUE THREAD

**Issue by mxttl1** [7eu7d7/genshin_auto_fish#242]
本地用的cu116，torch目前最高好像113
能找到torch1.10.2+cu113，但是找不到1.7.0+cu113
目前还在折腾各种bug中（这小水管torch太难下了）
刚装了cpu版本的折腾半天查到gpu_ids改-1才发觉这玩意坑了

**Comment by mxttl1** [comment]
目前遇到两个问题，一个解决了一个没解决。
其中一个，貌似线程问题导致，self.data_num_workers = 4修改为0临时解决，不知道大佬有正常解决方案没。
错误日志如下：
G:\ysfish\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-02-22 21:36:18 | INFO     | yolox.core.trainer:133 - Model Summary: Params: 5.03M, Gflops: 6.40
2022-02-22 21:36:18 | INFO     | yolox.core.trainer:286 - loading checkpoint for fine tuning
2022-02-22 21:36:18 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([6, 96, 1, 1]).
2022-02-22 21:36:18 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([6]).
2022-02-22 21:36:18 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([6, 96, 1, 1]).
2022-02-22 21:36:18 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([6]).
2022-02-22 21:36:18 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([6, 96, 1, 1]).
2022-02-22 21:36:18 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([6]).
2022-02-22 21:36:19 | INFO     | yolox.data.datasets.coco:45 - loading annotations into memory...
2022-02-22 21:36:19 | INFO     | yolox.data.datasets.coco:45 - Done (t=0.00s)
2022-02-22 21:36:19 | INFO     | pycocotools.coco:89 - creating index...
2022-02-22 21:36:19 | INFO     | pycocotools.coco:89 - index created!
2022-02-22 21:36:19 | INFO     | yolox.core.trainer:151 - init prefetcher, this might take one minute or less...
2022-02-22 21:36:43 | Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x000001FD11CFC860>>
Traceback (most recent call last):
  File "G:\ysfish\lib\site-packages\torch\utils\data\dataloader.py", line 1328, in __del__
ERROR    | yolox.core.launch:98 -     self._shutdown_workers()
An error has been caught in function 'launch', process 'MainProcess' (24536), thread 'MainThread' (2404):  File "G:\ysfish\lib\site-packages\torch\utils\data\dataloader.py", line 1295, in _shutdown_workers

Traceback (most recent call last):

  File "yolox_tools\    if self._persistent_workers or self._workers_status[worker_id]:
train.pyAttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
", line 132, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=8, cache=False, ckpt='weights/yolox_tiny.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "g:\ysfish\genshin_auto_fish\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001FD136498C8>

  File "yolox_tools\train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001FD08379E18>
    └ <yolox.core.trainer.Trainer object at 0x000001FD13655EF0>

  File "g:\ysfish\genshin_auto_fish\yolox\core\trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000001FD1362DD90>
    └ <yolox.core.trainer.Trainer object at 0x000001FD13655EF0>

  File "g:\ysfish\genshin_auto_fish\yolox\core\trainer.py", line 152, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x000001FD1C97C9B0>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x000001FD13655EF0>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x000001FD13655EF0>

  File "g:\ysfish\genshin_auto_fish\yolox\data\data_prefetcher.py", line 17, in __init__
    self.loader = iter(loader)
    │                  └ <yolox.data.dataloading.DataLoader object at 0x000001FD1C97C9B0>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x000001FD1C7E5BA8>

  File "G:\ysfish\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
           │    └ <function DataLoader._get_iterator at 0x000001FD11C5B158>
           └ <yolox.data.dataloading.DataLoader object at 0x000001FD1C97C9B0>

  File "G:\ysfish\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           │                              └ <yolox.data.dataloading.DataLoader object at 0x000001FD1C97C9B0>
           └ <class 'torch.utils.data.dataloader._MultiProcessingDataLoaderIter'>

  File "G:\ysfish\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
    │ └ <function BaseProcess.start at 0x000001FCB990F2F0>
    └ <Process(Process-2, initial daemon)>

  File "G:\ysfish\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process(Process-2, initial daemon)>
    │    │        │    └ <staticmethod object at 0x000001FCB990A668>
    │    │        └ <Process(Process-2, initial daemon)>
    │    └ None
    └ <Process(Process-2, initial daemon)>

  File "G:\ysfish\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process(Process-2, initial daemon)>
           │                └ <function DefaultContext.get_context at 0x000001FCB9960840>
           └ <multiprocessing.context.DefaultContext object at 0x000001FCB990AF98>

  File "G:\ysfish\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
           │     └ <Process(Process-2, initial daemon)>
           └ <class 'multiprocessing.popen_spawn_win32.Popen'>

  File "G:\ysfish\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
    │         │    │            └ <_io.BufferedWriter name=4>
    │         │    └ <Process(Process-2, initial daemon)>
    │         └ <function dump at 0x000001FCB990FE18>
    └ <module 'multiprocessing.reduction' from 'G:\\ysfish\\lib\\multiprocessing\\reduction.py'>

  File "G:\ysfish\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
    │              │     │              └ <Process(Process-2, initial daemon)>
    │              │     └ None
    │              └ <_io.BufferedWriter name=4>
    └ <class 'multiprocessing.reduction.ForkingPickler'>

BrokenPipeError: [Errno 32] Broken pipe

**Comment by mxttl1** [comment]
还有一个问题，看起来像浮点转整数，估计list的？
好吧不乱猜闹笑话，等大佬解决

100%|#####################################################################################################################################| 17/17 [00:05<00:00,  3.02it/s]
2022-02-22 21:32:38 | INFO     | yolox.evaluators.coco_evaluator:171 - Evaluate in main process...
2022-02-22 21:32:38 | INFO     | yolox.evaluators.coco_evaluator:204 - Loading and preparing results...
2022-02-22 21:32:38 | INFO     | yolox.evaluators.coco_evaluator:204 - DONE (t=0.01s)
2022-02-22 21:32:38 | INFO     | pycocotools.coco:362 - creating index...
2022-02-22 21:32:38 | INFO     | pycocotools.coco:362 - index created!
2022-02-22 21:32:39 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 0.00
2022-02-22 21:32:39 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (22648), thread 'MainThread' (22688):
Traceback (most recent call last):

  File "yolox_tools\train.py", line 132, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=8, cache=False, ckpt='weights/yolox_tiny.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "g:\ysfish\genshin_auto_fish\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000002480E18B8C8>

  File "yolox_tools\train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000024802FD9E18>
    └ <yolox.core.trainer.Trainer object at 0x000002480E198D68>

  File "g:\ysfish\genshin_auto_fish\yolox\core\trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x0000024802FD9F28>
    └ <yolox.core.trainer.Trainer object at 0x000002480E198D68>

  File "g:\ysfish\genshin_auto_fish\yolox\core\trainer.py", line 82, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x000002480E15DF28>
    └ <yolox.core.trainer.Trainer object at 0x000002480E198D68>

  File "g:\ysfish\genshin_auto_fish\yolox\core\trainer.py", line 207, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x000002480E15F268>
    └ <yolox.core.trainer.Trainer object at 0x000002480E198D68>

  File "g:\ysfish\genshin_auto_fish\yolox\core\trainer.py", line 303, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x000002480E198D68>
    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x0000024816C0A5F8>
    │          └ <yolox.core.trainer.Trainer object at 0x000002480E198D68>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "g:\ysfish\genshin_auto_fish\yolox\exp\yolox_base.py", line 288, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x000002480E144AE8>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x0000024816C0A5F8>

  File "g:\ysfish\genshin_auto_fish\yolox\evaluators\coco_evaluator.py", line 131, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([ 1.0057,  0.1017, 16.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 0, 'category_id': 1, 'bbox': [536.373291015625, 515.6226196289062, 47.123779296875, 53.8704833984375], 'score':...
                   │    └ <function COCOEvaluator.evaluate_prediction at 0x000002480E144BF8>
                   └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x0000024816C0A5F8>

  File "g:\ysfish\genshin_auto_fish\yolox\evaluators\coco_evaluator.py", line 212, in evaluate_prediction
    cocoEval = COCOeval(cocoGt, cocoDt, annType[1])
               │        │       │       └ ['segm', 'bbox', 'keypoints']
               │        │       └ <pycocotools.coco.COCO object at 0x000002481530C5F8>
               │        └ <pycocotools.coco.COCO object at 0x0000024816BF9AC8>
               └ <class 'yolox.layers.fast_coco_eval_api.COCOeval_opt'>

  File "G:\ysfish\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
    │    │        │              └ 'bbox'
    │    │        └ <class 'pycocotools.cocoeval.Params'>
    │    └ {}
    └ <yolox.layers.fast_coco_eval_api.COCOeval_opt object at 0x00000247A29967F0>

  File "G:\ysfish\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
    │    └ <function Params.setDetParams at 0x00000248328B7378>
    └ <pycocotools.cocoeval.Params object at 0x0000024822E027B8>

  File "G:\ysfish\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
    │              │  │                  │  └ <function round_ at 0x00000247A8661BF8>
    │              │  │                  └ <module 'numpy' from 'G:\\ysfish\\lib\\site-packages\\numpy\\__init__.py'>
    │              │  └ <function linspace at 0x00000247A89D4BF8>
    │              └ <module 'numpy' from 'G:\\ysfish\\lib\\site-packages\\numpy\\__init__.py'>
    └ <pycocotools.cocoeval.Params object at 0x0000024822E027B8>

  File "<__array_function__ internals>", line 6, in linspace

  File "G:\ysfish\lib\site-packages\numpy\core\function_base.py", line 113, in linspace
    num = operator.index(num)
          │        │     └ 10.0
          │        └ <built-in function index>
          └ <module 'operator' from 'G:\\ysfish\\lib\\operator.py'>

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by mxttl1** [comment]
最后跑起来还是有问题
Traceback (most recent call last):
  File "fishing.py", line 215, in <module>
    main(exp, args)
  File "fishing.py", line 117, in main
    model.load_state_dict(ckpt["model"])
  File "G:\ysfish\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([6]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([6]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([6]).

**Comment by 7eu7d7** [comment]
Broken pipe这个可能是CPU或者内存性能不够，可以不用多线程读数据。

**Comment by mxttl1** [comment]
> Broken pipe这个可能是CPU或者内存性能不够，可以不用多线程读数据。

也不一定是CPU火内存性能不够
我后面试出来就是页面文件被我强制设置为0导致的
打开后就能用了，也不用关闭多线程。
