### ISSUE TITLE
小白从py到develop的艰苦历程

### ISSUE THREAD

**Issue by FaVAVaF** [7eu7d7/genshin_auto_fish#244]
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.**
Successfully installed numpy-1.19.5
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Requirement already satisfied: torch==1.8.2+cpu in c:\users\asus\anaconda3\envs\ysfish\lib\site-packages (1.8.2+cpu)
Requirement already satisfied: numpy in c:\users\asus\anaconda3\envs\ysfish\lib\site-packages (from torch==1.8.2+cpu) (1.19.5)
Requirement already satisfied: typing-extensions in c:\users\asus\anaconda3\envs\ysfish\lib\site-packages (from torch==1.8.2+cpu) (4.1.1)
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Requirement already satisfied: torchvision==0.9.2+cpu in c:\users\asus\anaconda3\envs\ysfish\lib\site-packages (0.9.2+cpu)
Requirement already satisfied: thop in c:\users\asus\anaconda3\envs\ysfish\lib\site-packages (0.0.31.post2005241907)
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\asus\appdata\local\temp\pip-req-build-mqf17xs6
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\ASUS\AppData\Local\Temp\pip-req-build-mqf17xs6'
  fatal: unable to access 'https://github.com/philferriere/cocoapi.git/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\ASUS\AppData\Local\Temp\pip-req-build-mqf17xs6' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\ASUS\AppData\Local\Temp\pip-req-build-mqf17xs6' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 16, in pip_install
    check=True,
  File "C:\Users\ASUS\anaconda3\envs\ysfish\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\ASUS\\anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.

**Comment by FaVAVaF** [comment]
我按照网上的教程把这个numpy-1.19.5删除了，可是再运行的时候他又下载了回来。问了其他人，说改路径和卸载py其他版本，可我电脑上只有py3,7还有这个anaconda3。

**Comment by FaVAVaF** [comment]
改到d盘后可算出现了“successfully installed requirements!”但是ta还是显示了
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.

**Comment by FaVAVaF** [comment]
运行python setup.py develop又G了
running develop
running egg_info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt
C:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext
C:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
copying build\lib.win-amd64-3.7\yolox\_C.cp37-win_amd64.pyd -> yolox
Creating c:\users\asus\anaconda3\envs\ysfish\lib\site-packages\yolox.egg-link (link to .)
yolox 0.1.0 is already the active version in easy-install.pth

Installed d:\anaconda3\genshin_auto_fish
Processing dependencies for yolox==0.1.0
Finished processing dependencies for yolox==0.1.0

**Comment by FaVAVaF** [comment]
这是算成了还是不算

**Comment by FaVAVaF** [comment]
3.7裂开了只能用3.6了输入python setup.py develop
running develop
running egg_info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt
C:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext
C:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'yolox._C' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Windows\System32\genshin_auto_fish\yolox\layers\csrc -IC:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\include -IC:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\include\TH -IC:\Users\ASUS\anaconda3\envs\ysfish\lib\site-packages\torch\include\THC -IC:\Users\ASUS\anaconda3\envs\ysfish\include -IC:\Users\ASUS\anaconda3\envs\ysfish\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-ID:\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.10240.0\shared" "-ID:\Windows Kits\10\include\10.0.10240.0\um" "-ID:\Windows Kits\10\include\10.0.10240.0\winrt" /EHsc /TpC:\Windows\System32\genshin_auto_fish\yolox\layers\csrc\vision.cpp /Fobuild\temp.win-amd64-3.6\Release\Windows\System32\genshin_auto_fish\yolox\layers\csrc\vision.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
cl : Command line warning D9002 : ignoring unknown option '-O3'
vision.cpp
c1xx: fatal error C1083: Cannot open source file: 'C:\Windows\System32\genshin_auto_fish\yolox\layers\csrc\vision.cpp': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

这我卡住了

**Comment by HuYo-OS** [comment]
额，这个症状我见过很多次了，可以的话，我能帮你解决

**Comment by FaVAVaF** [comment]
> 额，这个症状我见过很多次了，可以的话，我能帮你解决

那大佬这个要怎么搞

**Comment by FaVAVaF** [comment]
> > 额，这个症状我见过很多次了，可以的话，我能帮你解决
> 
> 那大佬这个要怎么搞

我钓鱼还差几百条实在不想一条一条钓了，太痛苦了

**Comment by HuYo-OS** [comment]
提供一下vs的版本

**Comment by HuYo-OS** [comment]
WeChat：Leo_rebirth

**Comment by astror1o** [comment]
> WeChat：Leo_rebirth

同求解决办法

**Comment by astror1o** [comment]
同求解决办法 vs2019

**Comment by XenonChau** [comment]
> 期待原神能让更多的xdm喜欢上编程。
