### ISSUE TITLE
1400, 'GetWindowRect', '无效的窗口句柄。'

### ISSUE THREAD

**Issue by Chengshye** [7eu7d7/genshin_auto_fish#259]
Traceback (most recent call last):
  File "fishing.py", line 18, in <module>
    from fisher.environment import *
  File "D:\genshin_auto_fish-master\fisher\environment.py", line 4, in <module>
    from utils import *
  File "D:\genshin_auto_fish-master\utils\__init__.py", line 2, in <module>
    from .utils import *
  File "D:\genshin_auto_fish-master\utils\utils.py", line 30, in <module>
    gvars.genshin_window_rect = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

这是怎么回事呀呜呜呜……

**Comment by HuYo-OS** [comment]
请打开游戏之后再运行（注：命令行窗口要以管理员身份运行
