### ISSUE TITLE
你好，这个问题怎么解决？

### ISSUE THREAD

**Issue by 91hxs** [7eu7d7/genshin_auto_fish#263]
error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\1084797681\AppData\Local\Temp\pip-req-build-smrcqleb' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\1084797681\AppData\Local\Temp\pip-req-build-smrcqleb' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "C:\Windows\System32\genshin_auto_fish\requirements.py", line 74, in <module>
    main()
  File "C:\Windows\System32\genshin_auto_fish\requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "C:\Windows\System32\genshin_auto_fish\requirements.py", line 13, in pip_install
    subprocess.run(
  File "C:\Users\1084797681\anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\1084797681\\anaconda3\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status [](1.![问题](https://user-images.githubusercontent.com/79378310/160286395-8b40fd04-5505-4372-a574-0379b8de27a8.PNG))
![问题](https://user-images.githubusercontent.com/79378310/160286481-4d52d585-7093-410e-8434-5cbffe97b62a.PNG)

**Comment by WeatherWind** [comment]
提前装一下cocoapi呢？
