### ISSUE TITLE
在执行 python requirements.py 时出现了以下问题

### ISSUE THREAD

**Issue by 91hxs** [7eu7d7/genshin_auto_fish#264]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Collecting torch==1.8.2+cpu
  Using cached https://download.pytorch.org/whl/lts/1.8/cpu/torch-1.8.2%2Bcpu-cp38-cp38-win_amd64.whl (191.8 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from torch==1.8.2+cpu) (1.19.5)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.8.2+cpu typing-extensions-4.1.1
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Collecting torchvision==0.9.2+cpu
  Using cached https://download.pytorch.org/whl/lts/1.8/cpu/torchvision-0.9.2%2Bcpu-cp38-cp38-win_amd64.whl (847 kB)
Installing collected packages: torchvision
Successfully installed torchvision-0.9.2+cpu
Collecting thop
  Using cached thop-0.0.31.post2005241907-py3-none-any.whl (8.7 kB)
Installing collected packages: thop
Successfully installed thop-0.0.31.post2005241907
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\1084797681\appdata\local\temp\pip-req-build-c5m0atie
  ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 13, in pip_install
    subprocess.run(
  File "C:\ProgramData\Anaconda3\envs\ysfish\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.

**Comment by HuYo-OS** [comment]
安装一下git

**Comment by 91hxs** [comment]
> 安装一下git

你好，有没有相关的教程，我装了好几遍了，还是给我报错。不知道是我手法问题

**Comment by HuYo-OS** [comment]
实在不行来看看我的这个仓库吧https://github.com/HuYo-OS/Genshin_auto_fish

**Comment by 91hxs** [comment]
> 不能来看看我的仓库的实际情况吧https://github.com/HuYo-OS/Genshin_auto_fish

[Visual Studio]需要安装什么部分？我按照你的仓库的教程试了出现以下代码报错

执行pip install -r requirements.txt
报错
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

执行python requirements.py
报错
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.

最大的问题是，我安装git成功了但还是报错
ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

其中执行python setup.py develop这个命令，出现安装一晚上还未安装的情况。

而且不知道是不是我的理解问题，按照教程一步一步来都会出现以上的错误。希望能得到您的帮助。
