### ISSUE TITLE
安装pip和cuda版本提示的安装冲突

### ISSUE THREAD

**Issue by jiegunjun** [7eu7d7/genshin_auto_fish#266]
![20}_J~3)8Z(YJL3WQVY)`6L](https://user-images.githubusercontent.com/93933437/160634503-ade52b57-1516-45f5-b8ac-21337b4e567d.png)

**Comment by jiegunjun** [comment]
第一个是真的不理解

**Comment by jiegunjun** [comment]
[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pycocotools did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running install
      running build
      running build_py
      running build_ext
      building 'pycocotools._mask' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 22, in pip_install
    check=True,
  File "D:\Program Files\Anaconda\envs\ysfish\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:\\Program Files\\Anaconda\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', '--proxy=127.0.0.1:7890', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.
(ysfish) PS E:\genshin_auto_fish>

**Comment by LuckyZcs** [comment]
在这个网站 https://download.pytorch.org/whl/torch_stable.html 找cu114对应的torch和torchvision版本，然后自己到requirements.py里修改这两个版本号，并且后面网址换源为上面那个。numpy那个要不手动降imageio的版本为2.15，要不别限制numpy版本试试。
