### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by ffshff** [7eu7d7/genshin_auto_fish#268]
Collecting numpy==1.19.5
  Using cached numpy-1.19.5-cp38-cp38-win_amd64.whl (13.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.3
    Uninstalling numpy-1.22.3:
      Successfully uninstalled numpy-1.22.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5

**Comment by ffshff** [comment]
不过最后还是显示了successfully installed requirements!
后面的指令也都能跑
2022-04-01 23:59:11.971 | INFO     | __main__:main:101 - Model Summary: Params: 5.03M, Gflops: 15.15
2022-04-01 23:59:11.973 | INFO     | __main__:main:114 - loading checkpoint
2022-04-01 23:59:12.052 | INFO     | __main__:main:118 - loaded checkpoint done.
INIT OK
Waiting for "r" to perform fishing

不过按下R后钓鱼不能正常钓，搜索一会后就
Traceback (most recent call last):
  File "D:\Program\genshin_auto_fish\fisher\environment.py", line 126, in throw_rod
    obj_list, outputs, img_info = self.predictor.image_det(cap(), with_info=True)
TypeError: cannot unpack non-iterable NoneType object
2022-04-02 00:01:03.403 | INFO     | fisher.predictor:inference:77 - Infer time: 0.3491s
Traceback (most recent call last):
  File "D:\Program\genshin_auto_fish\fisher\environment.py", line 126, in throw_rod
    obj_list, outputs, img_info = self.predictor.image_det(cap(), with_info=True)
TypeError: cannot unpack non-iterable NoneType object
2022-04-02 00:01:03.763 | INFO     | fisher.predictor:inference:77 - Infer time: 0.3351s

**Comment by ffshff** [comment]
我的屏幕是2560*1600，调成1080窗口后能钓到一条鱼了，不过换鱼饵换不成功，然后才出的Type error

**Comment by KazilanBigAss** [comment]
我也有这个问题
