### ISSUE TITLE
救命 python setup.py develop 失敗

### ISSUE THREAD

**Issue by KobeRyanX** [7eu7d7/genshin_auto_fish#271]
(ysfish) C:\Users\s12da\Documents\Java\genshin_auto_fish>python setup.py develop
running develop
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt
reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext
C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:322: UserWarning: Error checking compiler version for cl: [WinError 2] 系統找不到指定的檔案。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'yolox._C' extension
Emitting ninja build file C:\Users\s12da\Documents\Java\genshin_auto_fish\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\TH -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\THC -IC:\Users\s12da\anaconda3\envs\ysfish\include -IC:\Users\s12da\anaconda3\envs\ysfish\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include" -c C:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.cpp /FoC:\Users\s12da\Documents\Java\genshin_auto_fish\build\temp.win-amd64-3.8\Release\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.obj -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/s12da/Documents/Java/genshin_auto_fish/build/temp.win-amd64-3.8/Release/Users/s12da/Documents/Java/genshin_auto_fish/yolox/layers/csrc/cocoeval/cocoeval.obj
cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\TH -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\THC -IC:\Users\s12da\anaconda3\envs\ysfish\include -IC:\Users\s12da\anaconda3\envs\ysfish\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include" -c C:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.cpp /FoC:\Users\s12da\Documents\Java\genshin_auto_fish\build\temp.win-amd64-3.8\Release\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.obj -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
cl : 命令列 warning D9002 : 忽略未知的選項 '-O3'
注意: 包含檔案: C:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\cocoeval\cocoeval.h
注意: 包含檔案:  C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11/numpy.h
注意: 包含檔案:   C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\pybind11.h
注意: 包含檔案:    C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\attr.h
注意: 包含檔案:     C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\cast.h
注意: 包含檔案:      C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\pytypes.h
注意: 包含檔案:       C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\detail/common.h
注意: 包含檔案:        C:\Users\s12da\anaconda3\envs\ysfish\include\Python.h
注意: 包含檔案:         C:\Users\s12da\anaconda3\envs\ysfish\include\patchlevel.h
注意: 包含檔案:         C:\Users\s12da\anaconda3\envs\ysfish\include\pyconfig.h
C:\Users\s12da\anaconda3\envs\ysfish\include\pyconfig.h(59): fatal error C1083: 無法開啟包含檔案: 'io.h': No such file or directory
[2/2] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\TH -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\THC -IC:\Users\s12da\anaconda3\envs\ysfish\include -IC:\Users\s12da\anaconda3\envs\ysfish\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include" -c C:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\vision.cpp /FoC:\Users\s12da\Documents\Java\genshin_auto_fish\build\temp.win-amd64-3.8\Release\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\vision.obj -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/s12da/Documents/Java/genshin_auto_fish/build/temp.win-amd64-3.8/Release/Users/s12da/Documents/Java/genshin_auto_fish/yolox/layers/csrc/vision.obj
cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\TH -IC:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\THC -IC:\Users\s12da\anaconda3\envs\ysfish\include -IC:\Users\s12da\anaconda3\envs\ysfish\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include" -c C:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\vision.cpp /FoC:\Users\s12da\Documents\Java\genshin_auto_fish\build\temp.win-amd64-3.8\Release\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\vision.obj -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
cl : 命令列 warning D9002 : 忽略未知的選項 '-O3'
注意: 包含檔案: C:\Users\s12da\Documents\Java\genshin_auto_fish\yolox\layers\csrc\cocoeval/cocoeval.h
注意: 包含檔案:  C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11/numpy.h
注意: 包含檔案:   C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\pybind11.h
注意: 包含檔案:    C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\attr.h
注意: 包含檔案:     C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\cast.h
注意: 包含檔案:      C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\pytypes.h
注意: 包含檔案:       C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\include\pybind11\detail/common.h
注意: 包含檔案:        C:\Users\s12da\anaconda3\envs\ysfish\include\Python.h
注意: 包含檔案:         C:\Users\s12da\anaconda3\envs\ysfish\include\patchlevel.h
注意: 包含檔案:         C:\Users\s12da\anaconda3\envs\ysfish\include\pyconfig.h
C:\Users\s12da\anaconda3\envs\ysfish\include\pyconfig.h(59): fatal error C1083: 無法開啟包含檔案: 'io.h': No such file or directory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    setuptools.setup(
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py", line 714, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\s12da\anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by HuYo-OS** [comment]
麻烦提交一下pytorch，（cuda，cudnn，如果你安装的是gpu版本的torch）版本

**Comment by KobeRyanX** [comment]
> 
我是使用cpu的，所以沒裝cuda，cudnn
