### ISSUE TITLE
YOLOX训练工作流程中报错

### ISSUE THREAD

**Issue by Open1Ya** [7eu7d7/genshin_auto_fish#286]
2022-06-12 17:33:31 | INFO     | yolox.core.trainer:132 - Model Summary: Params: 5.03M, Gflops: 6.44
2022-06-12 17:33:33 | INFO     | yolox.core.trainer:286 - loading checkpoint for fine tuning
2022-06-12 17:33:33 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([6, 96, 1, 1]).
2022-06-12 17:33:33 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([6]).
2022-06-12 17:33:33 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([6, 96, 1, 1]).
2022-06-12 17:33:33 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([6]).
2022-06-12 17:33:33 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([6, 96, 1, 1]).
2022-06-12 17:33:33 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([6]).
2022-06-12 17:33:33 | INFO     | yolox.data.datasets.coco:45 - loading annotations into memory...
2022-06-12 17:33:33 | INFO     | yolox.data.datasets.coco:45 - Done (t=0.00s)
2022-06-12 17:33:33 | INFO     | pycocotools.coco:89 - creating index...
2022-06-12 17:33:33 | INFO     | pycocotools.coco:89 - index created!
2022-06-12 17:33:33 | INFO     | yolox.core.trainer:151 - init prefetcher, this might take one minute or less...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Program Files (x86)\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Program Files (x86)\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Program Files (x86)\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\genshin_auto_fish-master\yolox_tools\train.py", line 10, in <module>
    import torch
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\Program Files (x86)\Python\Python38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
<img width="1280" alt="屏幕截图 2022-06-12 173455" src="https://user-images.githubusercontent.com/107345753/173227121-bf5f07ee-e2c5-42f0-acfd-84495c9a980c.png">
<img width="1280" alt="屏幕截图 2022-06-12 173628" src="https://user-images.githubusercontent.com/107345753/173227124-5e3dae45-6701-41dc-bdf2-12c5d6743c18.png">

**Comment by Open1Ya** [comment]
2022-06-12 17:33:33 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([6]).



OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\Program Files (x86)\Python\Python38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
