### ISSUE TITLE
运行python train_sim.py报错

### ISSUE THREAD

**Issue by PolarWS** [7eu7d7/genshin_auto_fish#288]
(ysfish) C:\Users\PolarWS\Downloads\genshin_auto_fish-weights>python train_sim.py
Traceback (most recent call last):
  File "train_sim.py", line 3, in <module>
    from fisher.environment import *
  File "C:\Users\PolarWS\Downloads\genshin_auto_fish-weights\fisher\environment.py", line 4, in <module>
    from pymouse import *
  File "C:\Users\PolarWS\anaconda3\envs\ysfish\lib\site-packages\pymouse\__init__.py", line 92, in <module>
    from windows import PyMouse, PyMouseEvent
ModuleNotFoundError: No module named 'windows'
以上是报错信息
但是我运行
(ysfish) C:\Users\PolarWS\Downloads\genshin_auto_fish-weights>pip install windows
Requirement already satisfied: windows in c:\users\polarws\anaconda3\envs\ysfish\lib\site-packages (0.1.1)
是正常的，请求大佬们解答

**Comment by pteromys1758** [comment]
不确定，你的问题在哪。但我碰到过类似的，最后发现我的问题在于，安装的版本不匹配。希望能给你提供一个思路。
