### ISSUE TITLE
安装依赖时出错

### ISSUE THREAD

**Issue by HuanLinMaster** [7eu7d7/genshin_auto_fish#291]
日志：
```
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\administrator\appdata\local\temp\pip-req-build-6hquoifm
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-6hquoifm'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-3.8\pycocotools
      running build_ext
      building 'pycocotools._mask' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-req-build-6hquoifm\PythonAPI\setup.py", line 25, in <module>
          cythonize(ext_modules)
        File "C:\Users\Administrator\anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "C:\Users\Administrator\anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\Administrator\anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pycocotools/_mask.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pycocotools did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running install
      C:\Users\Administrator\anaconda3\envs\ysfish\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'pycocotools._mask' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 13, in pip_install
    subprocess.run(
  File "C:\Users\Administrator\anaconda3\envs\ysfish\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.

(ysfish) D:\Project\genshin_auto_fish>python requirements.py
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: cython in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.29.30)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: scikit-image in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.19.3)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2022.5.4)
Requirement already satisfied: scipy>=1.4.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (1.8.1)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (1.3.0)
Requirement already satisfied: imageio>=2.4.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2.19.3)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (21.3)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (9.2.0)     
Requirement already satisfied: numpy>=1.17.0 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (1.19.5)
Requirement already satisfied: networkx>=2.2 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2.8.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from packaging>=20.0->scikit-image) (3.0.9)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: loguru in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.6.0)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from loguru) (1.1.0)
Requirement already satisfied: colorama>=0.3.4 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from loguru) (0.4.5)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: matplotlib in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (3.5.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (1.4.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (4.34.4)
Requirement already satisfied: numpy>=1.17 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (1.19.5)
Requirement already satisfied: cycler>=0.10 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: tabulate in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.8.10)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: tqdm in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (4.64.0)
Requirement already satisfied: colorama in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from tqdm) (0.4.5)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pywin32 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (304)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: PyAutoGUI in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.9.53)
Requirement already satisfied: mouseinfo in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.1.3)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.0.9)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.1.28)
Requirement already satisfied: pymsgbox in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (1.0.4)
Requirement already satisfied: pyrect in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from pygetwindow>=0.0.5->PyAutoGUI) (0.2.0)
Requirement already satisfied: Pillow>=6.2.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from pyscreeze>=0.1.21->PyAutoGUI) (9.2.0)
Requirement already satisfied: pyperclip in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from mouseinfo->PyAutoGUI) (1.8.2)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: PyYAML>=5.3.1 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (6.0)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: opencv_python in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.17.3 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from opencv_python) (1.19.5)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: keyboard in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.13.5)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: Pillow in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (9.2.0)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pymouse in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (1.0)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: numpy==1.19.5 in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (1.19.5)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Requirement already satisfied: torch==1.8.2+cpu in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (1.8.2+cpu)
Requirement already satisfied: typing-extensions in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from torch==1.8.2+cpu) (4.3.0)
Requirement already satisfied: numpy in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (from torch==1.8.2+cpu) (1.19.5)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Requirement already satisfied: torchvision==0.9.2+cpu in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.9.2+cpu)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: thop in c:\users\administrator\anaconda3\envs\ysfish\lib\site-packages (0.1.1.post2207130030)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\administrator\appdata\local\temp\pip-req-build-bbdzfg3v
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-bbdzfg3v'
  fatal: unable to access 'https://github.com/philferriere/cocoapi.git/': OpenSSL SSL_read: Connection was reset, errno 10054
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-bbdzfg3v' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-bbdzfg3v' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 13, in pip_install
    subprocess.run(
  File "C:\Users\Administrator\anaconda3\envs\ysfish\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.
```

**Comment by 7eu7d7** [comment]
把requirements.py里面cocoapi的链接里github.com换成hub.fastgit.xyz试试

**Comment by HuanLinMaster** [comment]
> 把requirements.py里面cocoapi的链接里github.com换成hub.fastgit.xyz试试
这问题已经解决了，现在发生了无法移动视角的问题，您的代码与别的作者改过的代码都无法移动视角
已经尝试过管理员启动了
https://github.com/HuYo-OS/Genshin_auto_fish/issues/17
