### ISSUE TITLE
关于仿真环境模型代码的报错:python train_sim.py

### ISSUE THREAD

**Issue by K1r1y** [7eu7d7/genshin_auto_fish#322]
(ysfishing) E:\genshin_auto_fish>python train_sim.py

Collecting experience...
Traceback (most recent call last):
  File "train_sim.py", line 47, in <module>
    agent.store_transition(s, a, r, s_, int(done))
  File "E:\genshin_auto_fish\fisher\agent.py", line 45, in store_transition
    transition = np.hstack((s, [a, r], s_, done))  # horizontally stack these vectors
  File "<__array_function__ internals>", line 200, in hstack
  File "D:\Anaconda3\envs\ysfishing\lib\site-packages\numpy\core\shape_base.py", line 363, in hstack
    arrs = atleast_1d(*tup)
  File "<__array_function__ internals>", line 200, in atleast_1d
  File "D:\Anaconda3\envs\ysfishing\lib\site-packages\numpy\core\shape_base.py", line 65, in atleast_1d
    ary = asanyarray(ary)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
以上的报错请求大佬救救
代码能跑起来自动钓鱼,就是这个python train_sim.py会报错,然后就缺少一个399的模型,原神游戏内的训练就跑不了

**Comment by K1r1y** [comment]
已解决

**Comment by K1r1y** [comment]
已解决

**Comment by yddnrg** [comment]
好兄弟，怎么解决的
