### ISSUE TITLE
Traceback (most recent call last):   File "yolox_tools/train.py", line 10, in <module>     import torch

### ISSUE THREAD

**Issue by mroldx** [7eu7d7/genshin_auto_fish#49]
Traceback (most recent call last):
  File "yolox_tools/train.py", line 10, in <module>
    import torch
  File "D:\Program Files\python\envs\ysfish_1\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\Program Files\python\envs\ysfish_1\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

**Comment by LemOnByn** [comment]
torch模块没有安装好，建议**pip list**看一下是不是在环境里了
