### ISSUE TITLE
五个环境全爆这个

### ISSUE THREAD

**Issue by mroldx** [7eu7d7/genshin_auto_fish#52]
'config_settings': config_settings
  File "D:\Program Files\python\envs\ysfish2\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 328, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "D:\Program Files\python\envs\ysfish2\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "D:\Program Files\python\envs\ysfish2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'

**Comment by YwEwanHuang** [comment]
试试

pip install setuptools
