### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboard'

### ISSUE THREAD

**Issue by mroldx** [7eu7d7/genshin_auto_fish#53]
python yolox_tools/train.py -f yolox/exp/yolox_tiny_fish.py -d 1 -b 8 --fp16 -o -c weights/yolox_tiny.pth
Traceback (most recent call last):
  File "yolox_tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "d:\d_git_project_file_workspace\python\genshin_auto_fish\yolox\core\__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "d:\d_git_project_file_workspace\python\genshin_auto_fish\yolox\core\trainer.py", line 12, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\Program Files\python\envs\ysfish2\lib\site-packages\torch\utils\tensorboard\__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'

**Comment by Faithlv-1** [comment]
缺少的包或者模块添加到Python添加默认模块搜索路径就行了。
在site-packages添加一个路径文件（假设你现在的python默认是：/usr/local/lib/python2.7/），
在 /usr/local/lib/python2.7/site-packages 路径下 新建一个文件 “mypkpath.pth”，文件里面的内容是 你想要加入的模块文件所在的目录名称。
例如：
新建文件：/usr/local/lib/python2.7/site-packages/mypkpath.pth
该文件内容：/usr/lib/python2.6/site-packages/
前面尝试几个都可以，但是在enum_type_wrapper 模块使用此方法无效，不太清楚什么问题，也许和python版本有关
https://blog.csdn.net/jdbc/article/details/80351833

**Comment by 7eu7d7** [comment]
参考 #59
