### ISSUE TITLE
运行钓鱼AI报no module named pyautogui

### ISSUE THREAD

**Issue by mroldx** [7eu7d7/genshin_auto_fish#57]
python fishing.py image -f yolox/exp/yolox_tiny_fish.py -c weights/best_tiny3.pth --conf 0.25 --nms 0.45 --tsize 640 --device cpu
Traceback (most recent call last):
  File "fishing.py", line 18, in <module>
    from fisher.environment import *
  File "D:\D_Git_Project_FIle_WorkSpace\python\genshin_auto_fish\fisher\environment.py", line 2, in <module>
    from utils import *
  File "D:\D_Git_Project_FIle_WorkSpace\python\genshin_auto_fish\utils\__init__.py", line 2, in <module>
    from .utils import *
  File "D:\D_Git_Project_FIle_WorkSpace\python\genshin_auto_fish\utils\utils.py", line 2, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'

**Comment by Sjqniubi** [comment]
一样的问题

**Comment by 7eu7d7** [comment]
再运行一遍requirements.py试试，不行手动安装
