### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1) YOLOX训练出错

### ISSUE THREAD

**Issue by Matt0o0** [7eu7d7/genshin_auto_fish#71]
![image](https://user-images.githubusercontent.com/44046317/134469883-cff5c244-dc70-4624-95c2-9e5ea41b46ad.png)
2021-09-23 15:30:49 | INFO     | yolox.data.datasets.coco:45 - loading annotations into memory...
2021-09-23 15:30:49 | INFO     | yolox.data.datasets.coco:45 - Done (t=0.01s)
2021-09-23 15:30:49 | INFO     | pycocotools.coco:89 - creating index...
2021-09-23 15:30:49 | INFO     | pycocotools.coco:89 - index created!
2021-09-23 15:30:49 | INFO     | yolox.core.trainer:151 - init prefetcher, this might take one minute or less...
'nvidia-smi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2021-09-23 15:31:03 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (24636), thread 'MainThread' (24100):
Traceback (most recent call last):

  File "yolox_tools\train.py", line 132, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=8, cache=False, ckpt='weights/yolox_tiny.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "c:\users\administrator\genshin_auto_fish\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001AD6665BAE8>

  File "yolox_tools\train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001AD659D80D0>
    └ <yolox.core.trainer.Trainer object at 0x000001AD66662CF8>

  File "c:\users\administrator\genshin_auto_fish\yolox\core\trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000001AD66633D90>
    └ <yolox.core.trainer.Trainer object at 0x000001AD66662CF8>

  File "c:\users\administrator\genshin_auto_fish\yolox\core\trainer.py", line 160, in before_train
    occupy_mem(self.local_rank)
    │          │    └ 0
    │          └ <yolox.core.trainer.Trainer object at 0x000001AD66662CF8>
    └ <function occupy_mem at 0x000001AD6567A840>

  File "c:\users\administrator\genshin_auto_fish\yolox\utils\metric.py", line 35, in occupy_mem
    total, used = get_total_and_free_memory_in_Mb(cuda_device)
                  │                               └ 0
                  └ <function get_total_and_free_memory_in_Mb at 0x000001AD6567A7B8>

  File "c:\users\administrator\genshin_auto_fish\yolox\utils\metric.py", line 27, in get_total_and_free_memory_in_Mb
    total, used = devices_info[int(cuda_device)].split(",")
                  │                └ 0
                  └ ['']

ValueError: not enough values to unpack (expected 2, got 1)

(ysfish) C:\Users\Administrator\genshin_auto_fish>

**Comment by CenJieTeng** [comment]
#21 我也是同样问题，要安装cuda，有空在试试。如果只是使用，可以用已经训练好的数据https://github.com/7eu7d7/genshin_auto_fish#预训练权重下载
