### ISSUE TITLE
RuntimeError: The environment variable QT_API has the unrecognized value {!r};valid values are 'pyqt5', 'pyside2', 'pyqt', and 'pyside'

### ISSUE THREAD

**Issue by pathologyenigma** [7eu7d7/genshin_auto_fish#82]
Traceback (most recent call last):
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\backends\qt_compat.py", line 64, in <module>
    QT_API = _ETS[QT_API_ENV]
KeyError: '5.15.2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fishing.py", line 18, in <module>
    from fisher.environment import *
  File "C:\dev\genshin_auto_fish\fisher\environment.py", line 2, in <module>
    from utils import *
  File "C:\dev\genshin_auto_fish\utils\__init__.py", line 1, in <module>
    from .render import *
  File "C:\dev\genshin_auto_fish\utils\render.py", line 3, in <module>
    from matplotlib import pyplot as plt
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\__init__.py", line 703, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\pyplot.py", line 256, in switch_backend
    switch_backend(candidate)
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\patho\.conda\envs\ysfish\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\backends\backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\patho\.conda\envs\ysfish\lib\site-packages\matplotlib\backends\qt_compat.py", line 69, in <module>
    "'pyside'") from err
RuntimeError: The environment variable QT_API has the unrecognized value {!r};valid values are 'pyqt5', 'pyside2', 'pyqt', and 'pyside'

尝试安装了pyqt5，并没有解决该问题，看错误提示像是命令行参数的问题，没有找到相关issue
环境是miniconda，在最后运行ai的时候碰到的错误，系统是win11

**Comment by pathologyenigma** [comment]
没有用过python，但是看抛出的错误应该是传backend类型的地方传了个版本号吧，看版本号像是qt sdk的版本号
