### ISSUE TITLE
运行python requirements.py时提示

### ISSUE THREAD

**Issue by q764447890** [7eu7d7/genshin_auto_fish#90]
ERROR: Command errored out with exit status 1:
   command: 'd:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Home\AppData\Local\Temp\pip-wheel-gndo4ghc'
       cwd: C:\Users\Home\AppData\Local\Temp\pip-req-build-h8iz2ep1\PythonAPI
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.6\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'd:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\Home\AppData\Local\Temp\pip-req-build-h8iz2ep1
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Home\AppData\Local\Temp\pip-req-build-h8iz2ep1\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "d:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 972, in cythonize
      aliases=aliases)
    File "d:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "d:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Home\AppData\Local\Temp\pip-record-_09oty_7\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\ProgramData\Anaconda3\envs\ysfish\Include\pycocotools'
         cwd: C:\Users\Home\AppData\Local\Temp\pip-req-build-h8iz2ep1\PythonAPI
    Complete output (6 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-req-build-h8iz2ep1\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Home\AppData\Local\Temp\pip-record-_09oty_7\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\ProgramData\Anaconda3\envs\ysfish\Include\pycocotools' Check the logs for full command output.

**Comment by xfeng-eng** [comment]
https://floating.blog.csdn.net/article/details/120276522?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link这里可以解决
