### ISSUE TITLE
在最后一步运行的时候报错

### ISSUE THREAD

**Issue by killerwhite** [7eu7d7/genshin_auto_fish#99]
2021-09-25 18:58:43.210 | INFO     | __main__:main:91 - Args: Namespace(ckpt='weights/yolox_tiny.pth', conf=0.25, demo='image', device='cpu', exp_file='yolox/exp/yolox_tiny_fish.py', experiment_name='yolox_tiny_fish', fp16=False, fuse=False, legacy=False, model_dir='./weights/fish_genshin_net.pth', n_actions=2, n_states=3, name=None, nms=0.45, path='./assets/dog.jpg', step_tick=12, trt=False, tsize=640)
2021-09-25 18:58:43.391 | INFO     | __main__:main:101 - Model Summary: Params: 5.03M, Gflops: 15.15
2021-09-25 18:58:43.395 | INFO     | __main__:main:114 - loading checkpoint
Traceback (most recent call last):
  File "g:\Game\Genshin Impact\Third-party tools\genshin_auto_fish\fishing.py", line 190, in <module>
    main(exp, args)
  File "g:\Game\Genshin Impact\Third-party tools\genshin_auto_fish\fishing.py", line 117, in main
    model.load_state_dict(ckpt["model"], strict=False)
  File "D:\Python\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([6]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([6]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([6]).

**Comment by lrzlin** [comment]
我也是一样的报错

**Comment by lrzlin** [comment]
已解决 不要用readme里面的yolox_tiny.pth权重
使用Release里的三个权重文件即可 best_tiny3.pth fish_genshin_net.pth fish_sim_net.pth
@killerwhite 
@7eu7d7 请问是否可以修改描述避免误导 感谢
